### ISSUE TITLE
isValid on individual properties 

### ISSUE THREAD

**Issue by gpoitch** [lcoq/ember-validations#18]
Maybe im missing something obvious that is already available, but I'd like to bind to the validity of each property.

For example, to add an error class to a text field:

``` handlebars
{{view Ember.TextField valueBinding="content.username" classNameBinding="content.validationErrors.username.isValid::error}}
```

Thanks, and great work!

**Comment by gpoitch** [comment]
I got it working by just checking if it exists.

``` handlebars
{{view Ember.TextField valueBinding="content.username" classNameBindings="content.validationErrors.username:error}}
```

**Comment by akaravashkin** [comment]
If you will use .validateProperty('username') instead of overall .validate() - your 'error' class will be still presented on the field, because content.validationErrors.username lives after .validateProperty(). So better to use  content.validationErrors.username.length. It helps me and I hope this thought will help someone.
